# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_new_arrivals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_arrivals',
            old_name='description',
            new_name='description1',
        ),
        migrations.RenameField(
            model_name='new_arrivals',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='new_arrivals',
            old_name='price',
            new_name='price1',
        ),
        migrations.RenameField(
            model_name='new_arrivals',
            old_name='title',
            new_name='title1',
        ),
    ]
