# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180712_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_arrivals',
            name='category',
        ),
        migrations.DeleteModel(
            name='new_arrivals',
        ),
    ]
